# Generated by Django 4.1.7 on 2023-03-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DestinationSearchRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.TextField()),
                ("time_of_search", models.TextField()),
                ("sustainability_score", models.TextField()),
            ],
        ),
    ]
