# Generated by Django 4.1.7 on 2023-03-20 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="destinationsearchrecord",
            old_name="sustainability_score",
            new_name="origin",
        ),
    ]
